language: rust

services:
  - docker

addons:
  homebrew:
    packages:
    - gcc
    - curl
    - wget

os:
  - linux
  - osx

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then docker build -f Dockerfile -t build-img-temp .          ; fi

script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then docker run --rm -it -v $PWD:/root/project/ build-img-temp bash /root/project/build.sh          ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then bash build-osx.sh ; fi


env:
  global:
  - TWINE_REPOSITORY=https://test.pypi.org/legacy/
  - secure: S7ToHwoRrEvBsNtCVos49AFa3w2vXzRTUE/jrGnYereFxRlVCLJesXrlR7LDCTgpjcaCzYki+HTBCciszMa6iST/FsX9toOq9jiUAC2xsYBH23+jV6QENpgH4Y913C3mrHwWeJRNK7Ggifaj6DVBuflllki6fS3EBahgXRqF8urbwEW7fOrd8hdSrnrMcAWHdp0y6eGEnVTa0n01WZ6Wq3y+cUBtu0c1+z+oCuCbJ+XH3HR73oVBL0urRQiMDkv5ukZBx+RyziepoG7HCtGFbqanmyBAGoVDMvNZ+4Y92Oiah8QTlfvJK18gr4bRVsJx8LehEEF/Q3hSEoiexq8kIEiv7qmsY7OEzI8q+dAK6W5hF1XWrwgj1tp8hwKL4jV7Z/s0oPnaT3w8yO78q4+Zd1BH89rBLET3hH0yI0m9nKWL5k0isqDXiU+xXII70nDEIuW3eYknGKn2g0C/FJGrl0y/EErjqUWXvxRs5+DU2ViyGEdsx6EL6DEpUmCs6sMwHXRatCol1GqLE/KRxdhTqXa4GZesxcyxxItlufqJyj1oZTK2YsikqXWuApm7xLeARESIE6ixptBKJwZsjEgxL2SdTUZclC/Vr2gW5s1chPmDeUbXJ7SKlq+dUdBaRpwIpJxRilT0lD41H7cZ9DuxzHb+/1Yd0l52TUeCRabD/Rc=
  - secure: VDMyIABDkw/PdVCCmbwgtMgHRZkFQWPY7lvFfaQhMjBZhl6Iud6GjBdd+IJL11sCPMcSn4+LR89fSVbJ7qpGj5ptS6K4pmpgy/JfatJZTnK+X5RGSZA2PjTHZzvVoHs1CEwEdp8U/+XZc2y+5q+/WWLZpNB11QgHyY/HKNGKBO5AmVdi6X87acQgwAJcli5D2kcig74ZVl7PfHdmn6ILJIngOT8FVlYxqBkF9O0r7hscq1CC1Dl6/hLc/nikfutvL7qyuPEm7HZKiD0+Ejsbes7CvLPGPGIoZwL/pEO2AiYekZywFGOz8HYhVSekkHpreisJur3pZRyfsQHvUnkcmzlz5ZhqrzxAzhhcbXvwQwTog7Sdt4KL6CbnzoSxq5vtXaxgG1oEVoli+Et411JRiC3WDTcHhJnGD6MixMoYl4t3rhVUF4B7l9z0Ff2Vc0S8c//GF/ZRQ2flEKktk735eXpeDvbz5UKaJKVIKasRUnbNld3Ait7XE+NLt/73aYT3RtfTTBOcvHbSjWVI3ear+IMdd/aFVjlrlozvy7z/T5Fcj7v4kt4EBHJEVsvuTeEWMwsJBLfohG5m84j4txEhzcAffkl5sGR2INyspXAi7NwX8Ytp+1Xcurt8ZAmZTuyJddSamMe0MedkJ8xMYLGGGIYXx8RDPxsRHPd0fQ3Refw=
