jobs:
- job: linux
  pool: {vmImage: 'Ubuntu-16.04'}
  steps:
    - task: UsePythonVersion@0
    - bash: |
        apt-get update
        apt-get install -y wget curl build-essential

        curl https://sh.rustup.rs -sSf --proto '=https' --tlsv1.2 | sh -s -- -y
        source $HOME/.cargo/env
        rustup default nightly

        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        bash Miniconda3-latest-Linux-x86_64.sh -f -b -p /root/miniconda
        export PATH="/root/miniconda/bin:$PATH"
        conda init bash
        source /root/.bashrc

        conda create -y --name python37 python=3.7
        conda create -y --name python36 python=3.6
        conda create -y --name python35 python=3.5

        conda activate python37
        pip install -r requirements-dev.txt
        maturin build
        cargo test --no-default-features
        pytest -q test_options.py --benchmark-group-by=group

        conda activate python36
        pip install -r requirements-dev.txt
        maturin build
        cargo test --no-default-features
        pytest -q test_options.py --benchmark-group-by=group

        conda activate python35
        pip install -r requirements-dev.txt
        maturin build
        cargo test --no-default-features
        pytest -q test_options.py --benchmark-group-by=group

        # Upload the built wheels - requires env vars
        twine upload target/wheels/rdp_rust*.whl


    # - task: PublishBuildArtifacts@1
    #   inputs: {pathtoPublish: 'wheelhouse'}
# - job: macos
#   pool: {vmImage: 'macOS-10.13'}
#   steps:
#     - task: UsePythonVersion@0
#     - bash: |
#         python -m pip install --upgrade pip
#         pip install cibuildwheel==0.11.1
#         cibuildwheel --output-dir wheelhouse .
#     - task: PublishBuildArtifacts@1
#       inputs: {pathtoPublish: 'wheelhouse'}
# - job: windows
#   pool: {vmImage: 'vs2017-win2016'}
#   steps:
#     - {task: UsePythonVersion@0, inputs: {versionSpec: '2.7', architecture: x86}}
#     - {task: UsePythonVersion@0, inputs: {versionSpec: '2.7', architecture: x64}}
#     - {task: UsePythonVersion@0, inputs: {versionSpec: '3.5', architecture: x86}}
#     - {task: UsePythonVersion@0, inputs: {versionSpec: '3.5', architecture: x64}}
#     - {task: UsePythonVersion@0, inputs: {versionSpec: '3.6', architecture: x86}}
#     - {task: UsePythonVersion@0, inputs: {versionSpec: '3.6', architecture: x64}}
#     - {task: UsePythonVersion@0, inputs: {versionSpec: '3.7', architecture: x86}}
#     - {task: UsePythonVersion@0, inputs: {versionSpec: '3.7', architecture: x64}}
#     - script: choco install vcpython27 -f -y
#       displayName: Install Visual C++ for Python 2.7
#     - bash: |
#         python -m pip install --upgrade pip
#         pip install cibuildwheel==0.11.1
#         cibuildwheel --output-dir wheelhouse .
#     - task: PublishBuildArtifacts@1
#       inputs: {pathtoPublish: 'wheelhouse'}